Graphql subscription
instana/go-sensor pull request #394
Opened 2023-02-07 08:30 UTC by willianpc

2023-02-22 14:44 UTC, sanojsubran requested changes
Great work @willianpc !! I have mentioned some minor things as review comments. Please check it.

2023-02-23 13:05 UTC, willianpc commented on instrumentation/instagraphql/README.md
> +`instagraphql` offers the following method wrappers able to collect GraphQL query data:
This is a pattern that is copied over and over from other instrumentations.
Let me keep it this way for now, but I agree with you that we should review this.
Maybe we make an effort to rewrite this for all instrumentations that follow this confusing pattern.

Is that ok for you?

2023-02-23 13:21 UTC, sanojsubran commented on instrumentation/instagraphql/README.md
> +`instagraphql` offers the following method wrappers able to collect GraphQL query data:
Sounds good !!

2023-02-23 13:38 UTC, sanojsubran approved these changes
Great work !!

2023-02-23 13:54 UTC, merged