added support to anable opt-in for forwarding exit spans without an entry span
instana/go-sensor pull request #684
Opened 2024-03-20 11:50 UTC by Angith

Changes

* Introduce an environment variable INSTANA_ALLOW_EXIT_AS_ROOT. Based on the environment variable, either the exit spans will be sent to the agent or suppressed. 
* Add unit tests for the above changes.

2024-03-20 23:12 UTC, sanojsubran requested changes
Please check the review comments

2024-03-22 05:20 UTC, Angith commented on span.go
> +
It looks better, indeed 👍

2024-03-22 05:21 UTC, Angith commented on span_test.go
> +			name:      "env_disable_tag_false_exit_true",
Good suggestion. 👍

2024-03-22 05:22 UTC, Angith commented on span_test.go
> +	}
Yes. It looks good 👍

2024-03-22 06:40 UTC, Angith commented on util.go
> +	allowExitAsRoot = "INSTANA_ALLOW_EXIT_AS_ROOT"
done 👍

2024-03-25 15:36 UTC, sanojsubran approved these changes
Looks good to me. Good work @Angith !

2024-03-25 15:46 UTC, merged